name: gpumonenv
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.12
  - schedule >=1.2,<1.3
  - pynvml >=11.0,<11.4
  - numpy >=1.24,<1.25 
  - pandas >=2.0,<2.1 
  - matplotlib >=3.7,<3.8
