[project]
name = "gpu-memory-tracker"
version = "0.1.0"
description = "Tracks GPU memory usage over time as your simulation code is running"
authors = ["Andrei Berceanu <andreicberceanu@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-ppc64le"]

[system-requirements]
linux = "5.4.0"

[tasks]
tracker = "nohup python nvml.py > /dev/null 2>&1 &"
reader = "python nvml_reader.py"

[dependencies]
python = ">=3.11,<3.12"
schedule = ">=1.2,<1.3"
pynvml = ">=11.0,<11.4"
numpy = ">=1.24,<1.25"
pandas = ">=2.0,<2.1"
matplotlib = ">=3.7,<3.8"
